import "@/styles/globals.css"
import { UserProvider } from "./usercontext"

export const metadata= {
  title: 'Minerales Raros S.A.',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon/favicon-32x32.png',
    appleIcon: '/favicon/apple-touch-icon.png',
    androidIcon: '/favicon/android-chrome-192x192.png'
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
      <body>{children}</body>
      </UserProvider>
    </html>
  )
}
